name: Naxcraft
main: com.naxville.naxcraft.Naxcraft
version: 1.0
website: http://www.naxville.com/dev.php
author: Naxum

commands:
  city:
    description: Allows for teleportation to city hubs.
    usage: |
           /<command>
           
  titles:
    description: Displays info on titles.
    usage: |
           /<command>
           
  fire:
    description: Turns off fire trail until restart.
    usage: |
           /<command>

  level:
    description: Allows you to buy skills.
    usage: |
           /<command>
           
  save-all:
    description: Save the server!
    usage: |
           /<command>

  setspawn:
    description: Sets the spawnpoint of the world.
    usage: |
           /<command>

  chat:
    description: Lists chat channels.
    usage: |
           /<command>
           
  spawn:
    description: Teleports you to the world spawnpoint.
    usage: |
           /<command>
           
  potion:
    description: Gives you potion effects.
    usage: |
           /<command>
           
  stats:
    description: Shows the server stats.
    usage: |
           /<command>
         
  party:
    description: Does party things. For help use /party help
    usage: |
           /<command> help
           
  home:
    description: Teleports you to your home, if not set, the /spawn.
    usage: |
           /<command>
           /<command> <name>
           /<command> <add/remove> <name>
          
  who:
    description: Shows online players.
    usage: |
           /<command>
           
  help:
    description: Prints command information.
    usage: |
           /<command> [page]
           /<command> [command name]
    aliases: '?'
           
  property:
    description: Shows property related commands.
    usage: |
           /<command>
    aliases: pr
           
  ranks:
    description: Lists all ranks and their prefixes.
    usage: |
           /<command>
           
  flags:
    description: Lists all area flags and what they do.
    usage: |
           /<command>
           
  color:
    description: Shows all colors and changes player's name color.
    usage: |
           /<command> <color>
           
  enchant:
    description: Cheats!
    usage: |
           /<command>
           
  duplicate:
    description: Duplicates an item.
    usage: |
           /<command> [#]
           
  join:
    description: Promotes you to member for 16 iron.
    usage: |
           /<command>

           
  borders:
    description: Shows current property borders.
    usage: |
           /<command>
           
  noborders:
    description: Hides nearby property borders.
    usage: |
           /<command>
           
  bc:
    description: Attempts to buy the current chunk. Alias of /property buy chunk
    usage: |
           /<command>
           
  bf:
    description: Attempts to buy a flag. Alias of /property buy flag <name>
    usage: |
           /<command> <flagname>
           
  wg:
    description: Creation of warpgates.
    usage: |
           /<command> <create/delete> <name>
           /<command> <id> [id]
           /<command> <link> <gate> <dest1> [dest2...]
           /<command> <mulitlink> <gate1> <gate2> [gate3...]
    aliases: warpgate

  mob:
    description: Sets your mob spawners to a certain creature.
    usage: |
           /<command> <creatureType>
    
  spawnmob:
    description: Spawns a mob.
    usage: |
           /<command> <creature> [amount < 16]
    
  hat:
    description: Haha woo.
    usage: |
           /<command>
           
  feed:
    description: nom nom
    usage:
         |
         /<command> [name]
    
  transcend:
    description: Let's leave this world, baby.
    usage: |
           /<command>
           
  creative:
    description: Allows creative mode in flagged areas.
    usage: |
           /<command>
           
  strike:
    description: ZAP
    usage: |
           /<command> [player]
           
  boom:
    description: BAM
    usage: |
           /<command> [player]
           
  weather:
    description: Find the weather, set it.
    usage: |
           /<command>
           /<command> thunder [player]
           /<command> storm [player]
           /<command> clear [player]

  god:
    description: Makes a player invurnerable.
    usage: |
           /<command> [?] [player]
           Example: /<command> - God modes yourself
           Example: /<command> naxum - God modes Naxum
           Example: /<command> ? naxum - Shows if Naxum is a god
           
  stealth:
    description: Turns you invisible.
    usage: |
           /<command>
           
  title:
    description: Title command.
    usage: |
           /<command>
           
  super:
    description: Makes you super, you ignore area rules.
    usage: |
           /<command>
         
  give:
    description: Gives a player some items.
    usage: |
           /<command> <item[:data]> [target]
           Example: /<command> wood:1 - Gives you some Redwood!

  time:
    description: Sets the time of day.
    usage: |
           /<command> <day/night/bloodmoon>

  back:
    description: Brings you back to pre-teleport location.
    usage: |
           /<command>
           /<command> [target]
           
  tp:
    description: Teleports a player or all players somewhere else.
    usage: |
           /<command> <target> 
           Example: /tp naxum - Teleports you to Naxum
           Example: /tp deltakin naxum - Tp Deltakin to Naxum
           Example: /tp * naxum - tps everyone online to Naxum
           Example: /tp 5 72 10 - Tps you to coords 5, 72, 10
           Example: /tp naxum 5 72 10 - Tps Naxum to coords
  'yes':
    description: Gives a player permission to teleport to you.
    usage: |
           /<command>
  
  'no':
    description: Refuses a player from teleporting to you.
    usage: |
           /<command>
  
  tphere:
    description: Teleports players to you.
    usage: |
           /<command> <player> [player2...]
           Example: /tphere naxum - Teleports Naxum to you
           Example: /tphere naxum deltakin - Tps both to you

  tpthere:
    description: Teleports players to target block.
    usage: |
           /<command> <player> [player2...]

  motd:
    description: Sets the Message Of The Day.
    usage: |
           /<command> <message>

  modkit:
    description: Gives the moderator kit.
    usage: |
           /<command>
           
  kick:
    description: Kicks a player.
    usage: |
           /<command> <name> [reason for kick (optional)].
           
  drop:
    description: Toggles removal of players inv. on death.
    usage: |
           /<command> [player] [player2...]
           Example: /drop - Toggles your drops on death
           Example: /drop naxum - Toggles Naxum's drops on death

  freeze:
    description: Freezes a player in place.
    usage: |
           /<command> <player> [player2...]

  g:
    description: Sends chat in the global channel.
    usage: |
           /<command> [message]
           Example /g - Sets chat channel to global
           Example /g Hi - Says "Hi" in the global channel

  local:
    description: Sends chat in the local (nearby) channel.
    usage: |
           /<command> [message]
           Example /l - Sets chat channel to local
           Example /l Hi - Says "Hi" in the local channel
    aliases: l

  p:
    description: Sends chat in the party channel.
    usage: |
           /<command> [message]

  m:
    description: Sends a chat message to everyone in all worlds.
    usage: |
           /<command> [message]
           
  msg:
    description: Sends private message to a player
    usage: |
           /<command> <player> [message]
           Example /msg Delta Hi - Sends "Hi" to Delta
    aliases: tell

  r:
    description: Reply to last person you sent a message to
    usage: |
           /<command> [message]

  list:
    description: Retrieve a list of local players.
    usage: |
           /<command> 
           Example /list - Returns all players within shouting distance
           /<command> help - Shows all clan help info.
        
        
  kill:
    description: Kills the specified player.
    usage: |
           /<command> [player]

  promote:
    description: Promotes player to next rank
    usage: |
           /<command> [player]

  demote:
    description: Demotes player to previous rank
    usage: |
           /<command> [player]
           
  ignore:
    description: Ignores or unignores a player
    usage: |
           /<command> <name>
  me:
    description: To be re-added later.
    usage: |
           /<command>
           
  mail:
    description: Send mail (and attachments) to other players.
    usage: |
           /<command>
